#!/usr/bin/env python3
"""
pull_arxiv.py — Pull latest q-fin papers from arXiv and update live catalog.

Usage:
    python3 scripts/pull_arxiv.py --out knowledge/05-resources/arxiv-frontier-live.md
    python3 scripts/pull_arxiv.py --days 60 --max 100
"""
import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
import xml.etree.ElementTree as ET

NS = {
    "a": "http://www.w3.org/2005/Atom",
    "arxiv": "http://arxiv.org/schemas/atom",
}

ARXIV_BASE = "https://export.arxiv.org/api/query"
CATEGORIES = ["q-fin.ST", "q-fin.TR", "q-fin.GN", "q-fin.PR", "q-fin.RM"]


def fetch_arxiv(query: str, max_results: int = 30) -> list[dict]:
    """Pull papers from arXiv API."""
    url = ARXIV_BASE
    params = {
        "search_query": query,
        "max_results": max_results,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    }
    r = requests.get(url, params=params, headers={"User-Agent": "qualabinance/0.1"})
    r.raise_for_status()
    root = ET.fromstring(r.text)
    papers = []
    for entry in root.findall("a:entry", NS):
        title = entry.find("a:title", NS)
        if title is None or title.text is None:
            continue
        title_text = title.text.strip().replace("\n", " ")
        arxiv_id = entry.find("a:id", NS).text.split("/")[-1]
        published = entry.find("a:published", NS).text[:10]
        summary_el = entry.find("a:summary", NS)
        summary = summary_el.text.strip()[:300] + "..." if summary_el is not None and summary_el.text else ""
        authors = [a.find("a:name", NS).text for a in entry.findall("a:author", NS) if a.find("a:name", NS) is not None]
        category_el = entry.find("arxiv:primary_category", NS)
        category = category_el.attrib.get("term", "q-fin.?") if category_el is not None else "q-fin.?"
        papers.append({
            "arxiv_id": arxiv_id,
            "title": title_text,
            "date": published,
            "authors": authors[:3] + (["…"] if len(authors) > 3 else []),
            "summary": summary,
            "category": category,
            "url": f"https://arxiv.org/abs/{arxiv_id}",
        })
    return papers


def main() -> int:
    parser = argparse.ArgumentParser(description="Pull latest q-fin papers from arXiv")
    parser.add_argument("--out", default="knowledge/05-resources/arxiv-frontier-live.md",
                        help="Output markdown file")
    parser.add_argument("--days", type=int, default=30, help="Look back N days")
    parser.add_argument("--max", type=int, default=50, help="Max papers per category")
    args = parser.parse_args()

    all_papers = []
    for cat in CATEGORIES:
        print(f"  fetching cat:{cat} ...", end=" ", flush=True)
        try:
            papers = fetch_arxiv(f"cat:{cat}", args.max)
            print(f"got {len(papers)}")
            all_papers.extend(papers)
        except Exception as e:
            print(f"FAILED: {e}")
            continue

    # Dedupe by arxiv_id (papers in multiple categories)
    seen = set()
    deduped = []
    for p in all_papers:
        if p["arxiv_id"] not in seen:
            seen.add(p["arxiv_id"])
            deduped.append(p)
    all_papers = deduped

    # Sort by date desc
    all_papers.sort(key=lambda p: p["date"], reverse=True)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    header = f"""# 📜 arXiv Frontier — Live Snapshot

> **Live arXiv q-fin feed.** Auto-generated by `scripts/pull_arxiv.py` on **{today}**.
>
> Re-fetched: weekly recommended via `bash knowledge/maintenance-loop.sh weekly`

---

## 🆕 Latest submissions (last {args.days} days, sorted by date desc)

| Date | Category | Title | Authors | Links |
|---|---|---|---|---|
"""

    rows = []
    for p in all_papers[:args.max]:
        cat = p["category"].replace("q-fin.", "")
        authors = ", ".join(p["authors"])
        title_link = f"[{p['title']}]({p['url']})"
        rows.append(f"| {p['date']} | {cat} | {title_link} | {authors} | [`{p['arxiv_id']}`]({p['url']}) |")

    body = "\n".join(rows)

    footer = f"""

---

## 🔄 Re-fetch instructions

```bash
# Quick: just arXiv
python3 scripts/pull_arxiv.py --out {args.out}

# Full weekly refresh
bash knowledge/maintenance-loop.sh weekly

# Full monthly refresh (incl. HF, Kaggle, OpenAlex)
bash knowledge/maintenance-loop.sh monthly
```

## 📊 Stats

- **Refreshed:** {today}
- **Total unique papers in last {args.days} days:** {len(all_papers)}
- **Categories covered:** {", ".join(CATEGORIES)}
- **API:** arXiv export.arxiv.org (free, no key, rate-limited)

**Maintainer:** Qualabinance / QuantResearcher · **Mode:** 🔄 CONTINUOUS RESEARCH
"""

    out_path.write_text(header + body + footer)
    print(f"\n✅ Wrote {len(all_papers)} papers to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
